### ISSUE TITLE
Hard-coded openread causing errors

### ISSUE THREAD

**Issue by dworzanski** [discretelogics/TeaFiles.Py#2]
I am using Debian 8 Jessie (stable) and Python 3.4 installed from the stable repos.

Here is what the installation looked like:

```bash
tom@tomspc ~ $ sudo pip3 install teafiles
[sudo] password for tom: 
Downloading/unpacking teafiles
  Downloading teafiles-0.71%20dev.zip (44kB): 44kB downloaded
  Running setup.py (path:/tmp/pip-build-x9ggs07g/teafiles/setup.py) egg_info for package teafiles
    
Installing collected packages: teafiles
  Running setup.py install for teafiles
      File "/usr/local/lib/python3.4/dist-packages/teafiles/teafile.py", line 1310
        TeaFile.openread('C:\Users\hase\AppData\Local\DiscreteLogics\TeaShell\Dow\AA.day.tea')
                            ^
    SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
    
    
Successfully installed teafiles
Cleaning up...
```

When running this simple test program right out of the docs:
```python
from teafiles import *

tf = TeaFile.create("acme.tea", "Time Price Volume", "qdq", "Acme at NYSE", {"decimals": 2, "url": "acme.com"})
tf.write(DateTime(2011, 3, 4, 9, 0), 45.11, 4500)
tf.write(DateTime(2011, 3, 4, 10, 0), 46.33, 1100)
tf.close()
```

I get this result:

```bash
/usr/bin/python3.4 /home/tom/Desktop/teafiles/test.py
Traceback (most recent call last):
  File "/home/tom/Desktop/teafiles/test.py", line 31, in <module>
    from teafiles import TeaFile
  File "/usr/local/lib/python3.4/dist-packages/teafiles/__init__.py", line 16, in <module>
    from teafiles.teafile import *
  File "/usr/local/lib/python3.4/dist-packages/teafiles/teafile.py", line 1310
    TeaFile.openread('C:\Users\hase\AppData\Local\DiscreteLogics\TeaShell\Dow\AA.day.tea')
                        ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
```

A Windows user named `hase` seems to have hard-coded some data opening operation on line 1310 of `teafile.py`.

**Comment by thulka** [comment]
please simply use the sources from here to avoid any install issues.

**Comment by dworzanski** [comment]
Will do.

Thanks for the really neat project! :)

**Comment by thulka** [comment]
thank you!
